### ISSUE TITLE
[Off-topic] Curious

### ISSUE THREAD

**Issue by serialfuzzer** [MdUsmanAnsari/blooming-flowers-with-falling-leaves-pure-css#1]
Hi, I'm here from SoloLearn. You used to be in a group with Serena? I'm just curious to know what happened to her?

**Comment by MdUsmanAnsari** [comment]
She is busy in her life. we are doing youtube stuff. thanks for asking.😊

**Comment by serialfuzzer** [comment]
Glad that she's alive. Read somewhere that she passed away. Dang. Had to fact-check, and cross-verify data from various sources to get to you! Thanks :)
